name: demyx/docker-socket-proxy

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  master:
    runs-on: ubuntu-latest
    env:
      DEMYX_REPOSITORY: docker-socket-proxy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          username: demyx
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        run: |
          docker pull tecnativa/docker-socket-proxy
          docker build -t demyx/${{ env.DEMYX_REPOSITORY }} .
      - name: Test
        id: test
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker run -d --name=${{ env.DEMYX_REPOSITORY }} --entrypoint=top demyx/${{ env.DEMYX_REPOSITORY }}

          DEMYX_TEST="$(docker exec ${{ env.DEMYX_REPOSITORY }} haproxy -v 2>&1)"
          if [[ "$DEMYX_TEST" == *"HAProxy version"* ]]; then
            echo "$DEMYX_TEST"
          else
            exit 1
          fi
      - name: Version
        run: |
          DEMYX_DOCKER_SOCKET_PROXY_ALPINE_VERSION="$(docker exec --user=root ${{ env.DEMYX_REPOSITORY }} cat /etc/os-release | grep VERSION_ID | cut -c 12-)"
          DEMYX_DOCKER_SOCKET_PROXY_HAPROXY_VERSION="$(docker exec --user=root ${{ env.DEMYX_REPOSITORY }} haproxy -v | grep HA-Proxy | awk '{print $3}')"
          DEMYX_JQ="$(jq ".alpine = \"$DEMYX_DOCKER_SOCKET_PROXY_ALPINE_VERSION\" | .docker_socket_proxy = \"$DEMYX_DOCKER_SOCKET_PROXY_HAPROXY_VERSION\"" version.json)"

          # Update versions
          echo "$DEMYX_JQ" > version.json
          echo "DEMYX_DOCKER_SOCKET_PROXY_ALPINE_VERSION=$DEMYX_DOCKER_SOCKET_PROXY_ALPINE_VERSION
          DEMYX_DOCKER_SOCKET_PROXY_HAPROXY_VERSION=$DEMYX_DOCKER_SOCKET_PROXY_HAPROXY_VERSION" > VERSION
      - name: Push
        run: |
          # Not sure why this is being created?
          [[ -f typescript ]] && rm -f typescript

          DEMYX_CHECK_STATUS="$(git status)"
          if [[ "$DEMYX_CHECK_STATUS" != *"nothing to commit"* ]]; then
            git config --global user.name github-actions[bot]
            git config --global user.email github-actions[bot]@users.noreply.github.com
            git remote set-url origin https://demyxsh:${{ secrets.DEMYX_TOKEN }}@github.com/demyxsh/${{ env.DEMYX_REPOSITORY }}
            git add .
            git commit -m "Schedule Build #${{ github.run_id }}"
            git push
          fi

          docker push demyx/${{ env.DEMYX_REPOSITORY }}
